In [8]:
from numpy import *
a = array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [9]:
a = linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [13]:
a = arange(1,10,2)
print(a)

[1 3 5 7 9]


In [14]:
a = zeros(5)
a

array([0., 0., 0., 0., 0.])

In [18]:
a = linspace(1,10,10)
print(a/5)

[0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


In [20]:
a = array([1,2,3,4,5])
b = a
c = a.copy()
b[0] = 10
c[0] = 20
print(a)
print(b)
print(c)

[10  2  3  4  5]
[10  2  3  4  5]
[20  2  3  4  5]


In [24]:
a = array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [25]:
a.ndim

2

In [26]:
a.shape

(2, 3)

In [27]:
a.size

6

In [28]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
print(a[0][2])

3


In [34]:
print(a[0,1:3])

[2 3]


In [39]:
i = eye(5)

In [40]:
print(i[0:3,0:3])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
a = array([1,2,3,4,5])

In [43]:
print(mean(a))

3.0


In [44]:
print(std(a))

1.4142135623730951


In [45]:
print(var(a))

2.0


In [46]:
print(sum(a))

15


In [47]:
print(prod(a))

120


In [50]:
zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [58]:
print(ones([2,2]))

[[1. 1.]
 [1. 1.]]


In [60]:
a = array([1,3,5,7,9])
b = array([2,4,6,8])

In [62]:
print(concatenate([a,b]))

[1 3 5 7 9 2 4 6 8]


In [64]:
a=array([[2,3,4],[4,5,6],[7,8,9]])
b=array([[2,3,4],[4,5,6],[7,8,9]])
print(concatenate([a,b],axis= 0))

[[2 3 4]
 [4 5 6]
 [7 8 9]
 [2 3 4]
 [4 5 6]
 [7 8 9]]


In [65]:
print(hstack([a,b]))

[[2 3 4 2 3 4]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [66]:
print(vstack([a,b]))

[[2 3 4]
 [4 5 6]
 [7 8 9]
 [2 3 4]
 [4 5 6]
 [7 8 9]]


In [77]:
a = array([1,2,3,4,5,6])
a,b,c = split(a,[3,4])

In [78]:
print(a,b,c)

[1 2 3] [4] [5 6]


In [93]:
a = array([[2,3,4],[4,5,6],[7,8,9],[1,2,3]])


In [94]:
b,c = vsplit(a, 2)

In [96]:
print(b)
print(c)

[[2 3 4]
 [4 5 6]]
[[7 8 9]
 [1 2 3]]


In [102]:
b,c,d = hsplit(a, 3)
print(b)
print(c)
print(d)

[[2]
 [4]
 [7]
 [1]]
[[3]
 [5]
 [8]
 [2]]
[[4]
 [6]
 [9]
 [3]]
